services:
  db:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_auth" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: